# Generated by Django 5.0.4 on 2024-04-15 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutorDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_de_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('fecha_de_fallecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento')),
                ('profesion', models.CharField(max_length=50, verbose_name='Profesión')),
                ('nacionalidad', models.CharField(max_length=50, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='FraseDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.TextField(max_length=1000, verbose_name='cita')),
                ('autor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.autordb')),
            ],
        ),
    ]
