# Generated by Django 5.0.4 on 2024-04-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autordb',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RenameField(
            model_name='autordb',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AlterModelTable(
            name='autordb',
            table='AutorDb',
        ),
    ]
